---
- name: Create SSH user
  become: true
  ansible.builtin.user:
    name: "{{ ssh_user }}"
    shell: /bin/bash
    password: "{{ ssh_user_password }}"
    state: present

- name: Add SSH user to ssh allowed users
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    line: "AllowUsers {{ ssh_user }} vagrant"
    state: present
  notify: Reload SSH service

- name: Ensure SSH user can switch to erp and erp_admin users and restart odoo services
  become: true
  ansible.builtin.copy:
    content: |
      {{ ssh_user }} ALL=(erp) NOPASSWD: ALL
      {{ ssh_user }} ALL=(erp_admin) NOPASSWD: ALL
      {{ ssh_user }} ALL=NOPASSWD: /bin/systemctl restart odoo
    dest: "/etc/sudoers.d/{{ ssh_user }}"
    mode: '0440'
    owner: root
    group: root

- name: Create Sudo user
  become: true
  ansible.builtin.user:
    name: "{{ sudo_user }}"
    shell: /bin/bash
    groups: sudo
    append: true
    state: present

- name: Deny Sudo user to ssh
  become: true
  ansible.builtin.lineinfile:
    line: "DenyUsers {{ sudo_user }}"
    path: /etc/ssh/sshd_config
  notify: Reload SSH service

- name: Create system user
  become: true
  ansible.builtin.user:
    name: "{{ system_user }}"
    shell: /usr/sbin/nologin
    system: true
    state: present
