- name: Set up production-ready Odoo server
  hosts: all
  become: true
  vars:
    odoo_domain: 192.168.56.10
  roles:
    - role: users
    - role: common
    - role: postgresql
    - role: odoo
    - role: nginx